name: security
on: [push]
jobs:
  tartufo:
    name: tartufo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - run: pip install tartufo

      - run: tartufo --json --repo-path . --exclude-paths .tartufo-ignore
